# Generated by Django 6.1.1 on 2026-09-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="author_bio",
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
