# Generated by Django 6.1.1 on 2026-09-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscription",
            old_name="subcribe_at",
            new_name="subscribe_at",
        ),
    ]
